baseURL = 'https://zanonmarco.it/'
languageCode = 'en-us'
title = "ReyMerk's Blog"
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'marco-zan'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'zanonmarco01'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = "avatar.jpg"            # use local avatar image in "static" folder
  name = 'ReyMerk'
  bio = 'I am a deeply passionate hacker, I enjoy playing with computers, embedded devices and mess with computer security'


  # misc
  monoDarkIcon = false                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon
