baseURL = 'https://example.org/'
languageCode = 'en-us|it-it'
title = 'Reymerk Blog'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'marco-zan'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://gravatar.com/marcozanon0c3b810033'                 # gravatar email or image url
  name = 'ReyMerk'
  bio = 'I am a deeply passionate hacker, I enjoy playing with computers, embedded devices and mess with computer security'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = false                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon
